server:
  port: 8000

spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      routes:
        - id: service-auth
          uri: http://localhost:8100
          predicates:
            - Path=/api/auth/**
        - id: service-trading
          uri: http://localhost:8080
          predicates:
            - Path=/api/trading/**
#          filters:
#            - AuthenticationFilter
        - id: service-query
          uri: http://localhost:8081
          predicates:
            - Path=/api/query/**
          filters:
            - AuthenticationFilter

  data:
    redis:
      cluster:
        nodes:
          - localhost:7001
          - localhost:7002
          - localhost:7003
          - localhost:7004
          - localhost:7005
          - localhost:7006
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  main:
    web-application-type: reactive
